### ISSUE TITLE
lgthinq.class.php

### ISSUE THREAD

**Issue by dimitrabelder** [pifou25/jeedom-lgthinq-plugin#24]
Bonjour,

Les dernières mise à jour depuis le market plante le chargement des pages jeedom (gestions des plugins, Mise à jour, ...).

require(/var/www/html/mobile): failed to open stream: No such file or directory in /var/www/html/plugins/lgthinq/core/class/lgthinq.class.php on line 12

Désinstallation & réinstallation du plugin sans succès.

Merci de ton aide.

**Comment by pifou25** [comment]
Bonjour,
C'est la version mobile je suppose ? l'interface web mobile ou bien l'appli mobile ?

**Comment by pifou25** [comment]
probablement corrigé, n'hésite pas à réouvrir sinon.
